services:
  frontend:
    build: 
      context: ./frontend
    container_name: vnav-console-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    container_name: vnav-console-backend
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./core-infra:/app/core-infra
    restart: unless-stopped
